name: stpm
version: '${version}'

main: com.shizukio.mc.stpm.bukkit.StpmBukkitPlugin
api-version: '1.21.4'
load: POSTWORLD

authors: [ Shizukio ]
website: https://mc.shizukio.com

permissions:
  stpm.command:
    description: Allows using the /stpm command.
    default: op
